### ISSUE TITLE
Avoid calling functions until required

### ISSUE THREAD

**Issue by CeoFred** [hngi/sentry-my-customer-backend#100]
**What Functionality / Service / Endpoint would you like to add?**
Optimization fix for API controllers

**Describe this Functionality / Service / Endpoint**
Some functions should only be called when it's time to use them, for example, signing a jwt token before confirming if
the user account is found for a registration route is not necessary, saves time and space.

**Duplicate prevention**
None

**Describe how to intend to go about adding this feature**
I moved all codes to places where they should be called only when needed.

**Slack username**
@codemon

**Additional context**

**Comment by nerdyphil** [comment]
please can you explain how you plan to do this?

**Comment by CeoFred** [comment]
It's very simple logic, some functions are not meant to be called till when used, in some code I see signing a jwt before actually confirming some certain things at the end you may not use the output of the function

**Comment by naijauser** [comment]
Mentors have marked this as trivial. I'll close it now.
