### ISSUE TITLE
Password for the route "/user/new" is not hashed (encrypted)

### ISSUE THREAD

**Issue by buka4rill** [hngi/sentry-my-customer-backend#103]
**Describe the bug**
When a store admin is created using the "user/new" route, the password isn't encrypted.

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. With Postman: <url>/user/new
2. Type in the request body to be sent. 
3. Send the body
4. Error: it shows password and concatenates the string "this will be encrypted"

**Expected behavior**
Password should be hashed.

**Screenshots**
![Screenshot (234)](https://user-images.githubusercontent.com/45390219/85850069-fbc89400-b7a3-11ea-98f5-1f3bc3c93d81.png)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
I checked the Pull Requests tab to this repo, and found that this has been implemented. It should be tested to see if it works and the person who implemented should claim this ticket

**Slack username**
@buka4rill 

**Additional context**

**Comment by chinazaaa** [comment]
approved by @chinazaaa

**Comment by Megxos** [comment]
Approved by @Megxos

**Comment by Megxos** [comment]
You have been working on this for 7 hours now. It will soon be given to someone else.

**Comment by buka4rill** [comment]
I'm done

**Comment by buka4rill** [comment]
Would make PR right away

**Comment by buka4rill** [comment]
https://github.com/hngi/sentry-my-customer-backend/pull/116

**Comment by buka4rill** [comment]
![Screenshot (240)](https://user-images.githubusercontent.com/45390219/85889538-9399a280-b7e3-11ea-9de4-e1817a72be16.png)
![Screenshot (241)](https://user-images.githubusercontent.com/45390219/85889542-95fbfc80-b7e3-11ea-983d-a801a2a5efa0.png)
