### ISSUE TITLE
password reset api #53

### ISSUE THREAD

**Issue by Balikey** [hngi/sentry-my-customer-backend#104]
Needs to be tested

**Comment by chinazaaa** [comment]
explain

**Comment by Balikey** [comment]
So i made this pull request without testing it, it wasn't merged because i was told to test it. When i tested it  i was told to raise an issue.

**Comment by naijauser** [comment]
Ok. I've looked at #53 . What you should do is to refactor the code to use Mongoose and the already created user models in the `/models` directory. When you have done this, send a new PR. 

This issue will be closed now.
