### ISSUE TITLE
Check that email format is valid before registering user

### ISSUE THREAD

**Issue by judgegodwins** [hngi/sentry-my-customer-backend#110]
**What Functionality / Service / Endpoint would you like to add?**
Check for email validity before registering

**Describe this Functionality / Service / Endpoint**
A middleware for register/user to check that email is valid
**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
yes

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 
Cook a middleware for the register/user route to check that email being given is valid. dns module would be also be used to check for the domain validity

**Slack username**
Please include your slack username here
@judgegodwins
**Additional context**

**Comment by emasontech** [comment]
I want this

**Comment by chinazaaa** [comment]
Will you install any dependency here

**Comment by nerdyphil** [comment]
No new modules are allowed at the moment

**Comment by chinazaaa** [comment]
Will you install any dependency here

**Comment by chinazaaa** [comment]
Approved by @chinazaaa

**Comment by emasontech** [comment]
No dependesis

**Comment by kenny-67** [comment]
This is no longer an issue

**Comment by Megxos** [comment]
This is frontend work

**Comment by Megxos** [comment]
This is not valid
