### ISSUE TITLE
Server side validation of request body in the user route using @hapi/joi

### ISSUE THREAD

**Issue by Clish254** [hngi/sentry-my-customer-backend#114]
**What Functionality / Service / Endpoint would you like to add?**
A short statement
We should validate data sent by a user before saving it to the db or updating.
**Describe this Functionality / Service / Endpoint**
A clear and concise description of what you want to add.
I would like to use @hapi/joi for schema description and validation in the user route especially when adding or updating user details,this is already being done in the register and login routes using @hapi/joi so i wont be installing any additional package. With @hapi/joi we can respond with very detailed error messages if validation fails with just one line of code.This will make our code cleaner and our error messages clearer.
**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes, no one is looking to impliment this in the user/new or user/update routes yet
**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 
Creating a schema description of a user schema using @hapi/joi and validating the request body by comparing it with the schema we described using @hapi/joi e.g is the email a valid email?is the password at least 6 chareacters long.
**Slack username**
Please include your slack username here
@clish
**Additional context**
I think i've explained everything for now

**Comment by Clish254** [comment]
I'd like to work on this

**Comment by Ghvstcode** [comment]
Hey, @Clish254!!!! Someone else has already created an issue to validate the request body! Please do find another thing to work on!
