### ISSUE TITLE
API token not returned to user on registration

### ISSUE THREAD

**Issue by judgegodwins** [hngi/sentry-my-customer-backend#118]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Post to `/register/user` with necessary cred.

**Expected behavior**
Should return API token

**Screenshots**
![Screenshot from 2020-06-26 20-54-28](https://user-images.githubusercontent.com/38760034/85895870-5d622000-b7ef-11ea-8390-b4b90065aa79.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux]
 - Browser: Chrome
 - Version 80+

**How do you intend to solve this bug?**
Change vars to while creating new User to use `api_token` as prop since that's what is in the schema

**Slack username**
@judgegodwins

**Additional context**

**Comment by Megxos** [comment]
Approved

**Comment by judgegodwins** [comment]
I'll work on it

**Comment by chinazaaa** [comment]
approved by @chinazaaa
