### ISSUE TITLE
User can forget, reset and change password

### ISSUE THREAD

**Issue by neymarjimoh** [hngi/sentry-my-customer-backend#123]
**What Functionality / Service / Endpoint would you like to add?**
This includes  the user authentication functionality

**Describe this Functionality / Service / Endpoint**
- A user can ask for a resend of the verification link sent upon sign up
- A registered user upon sign in can forget his login credentials, this functionality will create a link for the user when requesting for a password reset and tokens will be embedded in this link which can expire also. This will be sent to the users email
- A logged in user can decide to change his password and update to a new one. This will need the authentication middleware to verify the user and the user fields will be validated
**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
No
**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
Please include your slack username here
**@jimoh19**

**Additional context**
This is a 4 in 1 feature which is very important for user authentication.

**Comment by neymarjimoh** [comment]
I can work on this if approved and accepted
Username is @jimoh19

**Comment by sandygudie** [comment]
I have worked on password recovery recovery and reset already sorry I didn't raise an issue

**Comment by chinazaaa** [comment]
This issue is not approved

**Comment by chinazaaa** [comment]
As you did not follow due process for raising an issue... there is a form to fill before creating an issue... Next time follow due process
