### ISSUE TITLE
Update User Route not working

### ISSUE THREAD

**Issue by buka4rill** [hngi/sentry-my-customer-backend#69]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. With postman: <url>/user/update/:user_id
2.  Put in a the Key-Value pair you want to update
3. Send the request body
4. {
        "message": "Did not receive any update values"
    }

**Expected behavior**
Should return a message that it has updated user details

**Screenshots**
![Screenshot (225)](https://user-images.githubusercontent.com/45390219/85727024-94044180-b6ee-11ea-8111-06d3f203e40a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**How do you intend to solve this bug?**
I will refactor and edit the code in the code base to update user's details with key-value pairs

**Slack username**
@buka4rill

**Additional context**
None

**Comment by Naijabas** [comment]
Try to use x-www-form-urlencoded and let's see output

**Comment by buka4rill** [comment]
Same issue!
![Screenshot (228)](https://user-images.githubusercontent.com/45390219/85731270-48ec2d80-b6f2-11ea-81d6-63e73ffb40cd.png)

**Comment by chinazaaa** [comment]
Approved by @chinazaaa

**Comment by nerdyphil** [comment]
Approved by **@nerdyphil **

**Comment by buka4rill** [comment]
Done...Fixed
![Screenshot (229)](https://user-images.githubusercontent.com/45390219/85733616-3d9a0180-b6f4-11ea-82d6-4270f00d41ac.png)

**Comment by nerdyphil** [comment]
@buka4rill link to pr

**Comment by buka4rill** [comment]
https://github.com/hngi/sentry-my-customer-backend/pull/71

**Comment by chinazaaa** [comment]
It's now working, merging PR
