### ISSUE TITLE
entry PORT not working 

### ISSUE THREAD

**Issue by emasontech** [hngi/sentry-my-customer-backend#73]
**Describe the bug**
the entry port was changed to 5000 but application runs on 3000, and the README file points to welcome page but actually its a dead page not found, secondly three is  no such welcome status 200 in the app., the entry point of app is actually a 404 error, i can fix this by changing the routh to point to documentation page then users can navigate 

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Go to '.env file ' and change port to 3000, then update RRADME to point to point to 3000
2 .go to routh update the routh to point to 'documentation"

**Expected behavior**
localhost:5000
automatically  renders documentation :

slack username @joshua
![entrypoint](https://user-images.githubusercontent.com/51678953/85744898-2875a080-b6fd-11ea-92a9-da3fdef81996.PNG)

after editing  will become

 entry point becomes  either
![expected](https://user-images.githubusercontent.com/51678953/85751434-7d67e580-b702-11ea-902e-ce8844f8b504.PNG)

or
![expected 2](https://user-images.githubusercontent.com/51678953/85751617-a2f4ef00-b702-11ea-8113-d9826469c277.PNG)

**Comment by tboy44wiz** [comment]
No no no. you're getting it all wrong. Run Locally before complaining.
Please First Pull Locally. Test with your PostMan and Share the Error Screen. 
Secondly the route you're on is not meant to give you any response rather than 404 error. That's the root route bro.

**Comment by buka4rill** [comment]
The entry port is 3000...I think it should be left like that. It works with port 3000

**Comment by emasontech** [comment]
it was stated in the README file so its missleading. pls show me your screenshot on entry point

**Comment by pesova** [comment]
change the readme to the right port

**Comment by jobafash** [comment]
Fix the typo and check that youre on the right track

**Comment by jobafash** [comment]
Approved by {{jobafash}}

**Comment by jobafash** [comment]
Approved by @jobafash

**Comment by pesova** [comment]
Approved by @pesova

**Comment by emasontech** [comment]
done README  changed..
