### ISSUE TITLE
MISSING FIELDS ON THE COMPLAINT API

### ISSUE THREAD

**Issue by Naijabas** [hngi/sentry-my-customer-backend#77]
**Describe the bug**
Whenever the complaint API is called, it's not returning the user name and email

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Just find the complaint API and make the necessary edits..

**Expected behavior**
It's supposed to able to display Email and User Name along with others

**Screenshots**
[image](https://user-images.githubusercontent.com/62475178/85755826-2f54e100-b706-11ea-8fdb-fae5f9d40243.png)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Me, I don't know oo

**Slack username**
@Naijabas 

**Additional context**

**Comment by chinazaaa** [comment]
Approved by @chinazaaa

**Comment by nerdyphil** [comment]
approved by @nerdyphil

**Comment by iAmServer** [comment]
@chinazaaa am taking this issue

**Comment by chinazaaa** [comment]
Okay

**Comment by iAmServer** [comment]
I have few questions regarding the API, who's to answer that for me please

**Comment by naijauser** [comment]
Drop any questions you have on the slack channel. @iAmServer

**Comment by iAmServer** [comment]
![Screen Shot 2020-06-26 at 3 47 59 AM](https://user-images.githubusercontent.com/23441882/85833591-f6e1f100-b75f-11ea-821b-e5a591378099.png)

@Naijabas @naijauser @chinazaaa @nerdyphil

**Comment by iAmServer** [comment]
Thats the final output

**Comment by chinazaaa** [comment]
still has issues
