### ISSUE TITLE
DATE IS SHOWING some "Z" and "T" ..

### ISSUE THREAD

**Issue by Naijabas** [hngi/sentry-my-customer-backend#78]
**Describe the bug**
The dates used on the database may be misleading people 

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

- Edit it On the Database,

**Expected behavior**
It should return something like this 2020-06-15 14:53:46

**Screenshots**

![image](https://user-images.githubusercontent.com/62475178/85757249-36302380-b707-11ea-9f7a-a285e3b01b6b.png)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
If I have access to the DB, I can do that..

**Slack username**
@Naijabas 
**Additional context**

**Comment by vicradon** [comment]
This is how MongoDB stores dates.

I don't think messing with this is a good idea

**Comment by Naijabas** [comment]
Ahhh
Okay oo
😔

**Comment by buka4rill** [comment]
lmao😂
