### ISSUE TITLE
Customer update route not working

### ISSUE THREAD

**Issue by kenny-67** [hngi/sentry-my-customer-backend#81]
**Describe the bug**
does not update customer information, it shows successful when you try to update but when you try fetching the updated customer details it returns the old details

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Go to "/customer/all" route and pick a random customer id
2. Go to "/customer/update/(the id selected from step 1 above)" and input the details to update in the body

then try fetching the customer details you would see it did not update

**Expected behavior**
The customer details is supposed to be updated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser Chrome

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
@kenneth_real

**Additional context**

**Comment by ajdelgados** [comment]
You should send a body like this in the request

{
    "name": "test",
    "phone": 8153632823
}

**Comment by kenny-67** [comment]
that's exactly what I did ...I got a success message but the database was not updated

**Comment by naijauser** [comment]
Approved by @naijauser

**Comment by kenny-67** [comment]
Thanks, fixing now...

**Comment by naijauser** [comment]
Assigned to @kenneth_real
