### ISSUE TITLE
validating  in backend using @hapiJoi

### ISSUE THREAD

**Issue by emasontech** [hngi/sentry-my-customer-backend#87]
**What Functionality / Service / Endpoint would you like to add?**
backed data validation during user registration
**Describe this Functionality / Service / Endpoint**

noticed there is no validation in any of the field during registration except validation will be done on front end , i will love to implement the back end validation for registration entered data 

**Duplicate prevention**
no duplication

**Describe how to intend to go about adding this feature**
I will install @hapyJoi. and create schema to validate entries

**Slack username**
**@joshua**  im interested to work on this task

**Additional context**
**user entries:** type, length, required, max,min, etc

**Comment by iAmServer** [comment]
@chinazaaa I will take this

**Comment by naijauser** [comment]
This is a duplicate #60 already addresses this.
