### ISSUE TITLE
Integrate Google Oauth.. 

### ISSUE THREAD

**Issue by emasontech** [hngi/sentry-my-customer-backend#90]
**What Functionality / Service / Endpoint would you like to add?**
Google Oauth for easy registration and login by users instead of going through registration log process

**Describe this Functionality / Service / Endpoint**
Better user expirience 
**Duplicate prevention**
No duplicate

**Describe how to intend to go about adding this feature**
1 install passport and Google Oauth passport
2 get API key from Google. 
3 write code to integrate the service
2 send user data to proper data formating API like create use API or send data start to database. 
2 automaticly login the user 
**Slack username**
**@joshua**
**Additional context**
Will love to work on this

**Comment by Hopekodi** [comment]
What's the difference between this and implement login with Google?

**Comment by naijauser** [comment]
Mentors have marked this as trivial.
