### ISSUE TITLE
Check if a user already exists before creating a new user.

### ISSUE THREAD

**Issue by Clish254** [hngi/sentry-my-customer-backend#96]
**What Functionality / Service / Endpoint would you like to add?**
In the /user/new endpoint we should check if a user already exists before creating a new user.

**Describe this Functionality / Service / Endpoint**
We should do something like User.findOne to check if the user already exists before doing User.create

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes
**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 
Using mongoose's User.findOne and passing the email from the request body,if a user already exists respond with error 400 "Email already exists"
**Slack username**
Please include your slack username here
@clish
**Additional context**
I think i've explained everything I can

**Comment by nerdyphil** [comment]
approved by @nerdyphil

**Comment by Clish254** [comment]
I am working on this now

**Comment by chinazaaa** [comment]
approved by @chinazaaa

**Comment by chinazaaa** [comment]
what's the format for testing

**Comment by chinazaaa** [comment]
waiting

**Comment by Clish254** [comment]
> what's the format for testing

Try to create a user with an email which already exists in the db,you'll just get an error message "Could not add user due to an internal error" which doesn't really say much,but if we check if a user already exists before trying to save, if a user already exists we can send an an error message "email already exists" which is more detailed.

**Comment by buka4rill** [comment]
I added this fix to my PR yesterday. If you are still working on this, please don't bother to push

**Comment by buka4rill** [comment]
![image](https://user-images.githubusercontent.com/45390219/85921066-292f4380-b871-11ea-8312-0fff9282df8b.png)

**Comment by chinazaaa** [comment]
so this issue is solved? Can i close it?

**Comment by buka4rill** [comment]
Yes, it's solve. I did it yesterday. If he feels it isn't he should test it and post screenshots

**Comment by chinazaaa** [comment]
okay closing
