### ISSUE TITLE
Root route shows 404 error

### ISSUE THREAD

**Issue by Megxos** [hngi/sentry-my-customer-backend#97]
**Describe the bug**
Root route (/) displays a 404 error page

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Go to **http://...domain.../
2. See error

**Expected behavior**
Root route should redirect to /docs

**Screenshots**
![Screenshot from 2020-06-26 10-15-16](https://user-images.githubusercontent.com/42103959/85841449-0ed46780-b796-11ea-8ba7-43cb4f1be461.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 19.10]
 - Browser [chrome]
 - Version [80.0.3987.132]

**How do you intend to solve this bug?**
Setting the root route to redirect to **/docs**

**Slack username**
@Mikah

**Additional context**

**Comment by nerdyphil** [comment]
Lgtm
approved by @nerdyphil

**Comment by naijauser** [comment]
Approved by @naijauser

**Comment by nerdyphil** [comment]
will you be the one solving it @Megxos?

**Comment by Megxos** [comment]
No let someone have it @naijauser

**Comment by cAtaman** [comment]
I'll like to take this

**Comment by chinazaaa** [comment]
assigned to @cAtaman

**Comment by Megxos** [comment]
How many hours is it taking you to do simple redirect? @cAtaman

**Comment by emasontech** [comment]
I stated this issue and person told. That's how it supposed to work I don't get what is Goin one here oh

**Comment by emasontech** [comment]
This is not fair, this was the  first issue I brought and and even complainted on the README documentation.. I even made a PR but yet you guys have not done anything

**Comment by emasontech** [comment]
Pls let  me do it now now.

**Comment by Megxos** [comment]
@emasontech  I opened this after thinking through it.

**Comment by emasontech** [comment]
Let me  fix it. Thanks

**Comment by cAtaman** [comment]
> How many hours is it taking you to do simple redirect? @cAtaman

Hey sorry about that, power issues... Thanks for taking the initiative
