### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by judgegodwins** [hngi/sentry-my-customer-backend#98]
**What Functionality / Service / Endpoint would you like to add?**
Email verification.

**Describe this Functionality / Service / Endpoint**
Email verification would ensure the email address of an owner is correct. 

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes

**Describe how to intend to go about adding this feature**
When users register they will be marked as not_activated until they have confirmed their email with an encrypted link sent.
The link would contain details of their accounts. 
When this link is opened, it'll be decrypted and it would return stringified json then it'll parsed into json.
And a middleware would be added to make sure that before registering, the email would be checked for correct format. I'll do this with mailgun and nodemailer.

**Slack username**
Please include your slack username here
@judgegodwins

**Additional context**

**Comment by iAmServer** [comment]
I think this is implemented already

**Comment by judgegodwins** [comment]
> I think this is implemented already

@iAmServer Nah, I don't think so

**Comment by judgegodwins** [comment]
@iAmServer Nah, don't think so

**Comment by naijauser** [comment]
Based on the application requirements, number verification is sufficient. I'll be closing this now.
